# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(515, 538)
        MainWindow.setFocusPolicy(QtCore.Qt.TabFocus)
        MainWindow.setStyleSheet("QPushButton{\n"
"background-color: silver;\n"
"border-radius:10;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:grey;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(2, 0, 511, 41))
        self.widget.setMinimumSize(QtCore.QSize(30, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainWindowButton = QtWidgets.QPushButton(self.widget)
        self.mainWindowButton.setMinimumSize(QtCore.QSize(30, 30))
        self.mainWindowButton.setObjectName("mainWindowButton")
        self.horizontalLayout.addWidget(self.mainWindowButton)
        self.closeButton = QtWidgets.QPushButton(self.widget)
        self.closeButton.setMinimumSize(QtCore.QSize(30, 30))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Player_turn = QtWidgets.QLabel(self.widget)
        self.Player_turn.setMinimumSize(QtCore.QSize(100, 10))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Player_turn.setFont(font)
        self.Player_turn.setObjectName("Player_turn")
        self.horizontalLayout.addWidget(self.Player_turn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 515, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.aSaveGame = QtWidgets.QAction(MainWindow)
        self.aSaveGame.setObjectName("aSaveGame")
        self.aLoadGame = QtWidgets.QAction(MainWindow)
        self.aLoadGame.setObjectName("aLoadGame")
        self.menu.addAction(self.aSaveGame)
        self.menu.addAction(self.aLoadGame)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.closeButton.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Моя игра"))
        self.mainWindowButton.setText(_translate("MainWindow", "Главное меню"))
        self.closeButton.setText(_translate("MainWindow", "Выйти"))
        self.Player_turn.setText(_translate("MainWindow", "Ходит игрок 1"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Настройки"))
        self.aSaveGame.setText(_translate("MainWindow", "Сохранить"))
        self.aLoadGame.setText(_translate("MainWindow", "Загрузить"))
