# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(515, 538)
        MainWindow.setFocusPolicy(QtCore.Qt.TabFocus)
        MainWindow.setStyleSheet("QPushButton{\n"
"background-color: silver;\n"
"border-radius:10;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:grey;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 100, 211, 111))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(2, 0, 511, 41))
        self.widget.setMinimumSize(QtCore.QSize(30, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playButton = QtWidgets.QPushButton(self.widget)
        self.playButton.setEnabled(True)
        self.playButton.setMinimumSize(QtCore.QSize(30, 30))
        self.playButton.setBaseSize(QtCore.QSize(20, 20))
        self.playButton.setObjectName("playButton")
        self.horizontalLayout.addWidget(self.playButton)
        self.stopButton = QtWidgets.QPushButton(self.widget)
        self.stopButton.setMinimumSize(QtCore.QSize(30, 30))
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.closeButton = QtWidgets.QPushButton(self.widget)
        self.closeButton.setMinimumSize(QtCore.QSize(30, 30))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.openButton = QtWidgets.QPushButton(self.widget)
        self.openButton.setMinimumSize(QtCore.QSize(30, 30))
        self.openButton.setObjectName("openButton")
        self.horizontalLayout.addWidget(self.openButton)
        self.secondOpenButton = QtWidgets.QPushButton(self.widget)
        self.secondOpenButton.setMinimumSize(QtCore.QSize(30, 30))
        self.secondOpenButton.setObjectName("secondOpenButton")
        self.horizontalLayout.addWidget(self.secondOpenButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 515, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.aSaveGame = QtWidgets.QAction(MainWindow)
        self.aSaveGame.setObjectName("aSaveGame")
        self.aLoadGame = QtWidgets.QAction(MainWindow)
        self.aLoadGame.setObjectName("aLoadGame")
        self.menu.addAction(self.aSaveGame)
        self.menu.addAction(self.aLoadGame)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.closeButton.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Моя игра"))
        self.label.setText(_translate("MainWindow", "Привет Мир!"))
        self.playButton.setText(_translate("MainWindow", "Play"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.closeButton.setText(_translate("MainWindow", "close"))
        self.openButton.setText(_translate("MainWindow", "open"))
        self.secondOpenButton.setText(_translate("MainWindow", "open"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Настройки"))
        self.aSaveGame.setText(_translate("MainWindow", "Сохранить"))
        self.aLoadGame.setText(_translate("MainWindow", "Загрузить"))
